# Generated by Django 5.1.4 on 2026-08-28 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_productvariant_attributes_measurementunit_and_more'),
        ('organizations', '0002_rename_organizatio_slug_c3d82b_idx_organizatio_slug_048085_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('unavailable', 'Unavailable'), ('disabled', 'Disabled')], default='available', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('measurement_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='catalog.measurementunit')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['product__name', 'variant__name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('manualAdjustment', 'Manual adjustment'), ('stockIn', 'Stock in'), ('stockOut', 'Stock out'), ('reservation', 'Reservation'), ('releaseReservation', 'Release reservation')], max_length=32)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reserved_delta', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('consumed', 'Consumed'), ('cancelled', 'Cancelled')], default='active', max_length=24)),
                ('source_type', models.CharField(blank=True, max_length=80)),
                ('source_key', models.CharField(blank=True, max_length=120)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.inventoryitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['organization', 'status'], name='inventory_i_organiz_7262e9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['organization', 'product'], name='inventory_i_organiz_8dd42f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['organization', 'variant'], name='inventory_i_organiz_e508bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('organization', 'product'), name='inventory_item_unique_product_without_variant'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('organization', 'product', 'variant'), name='inventory_item_unique_product_variant'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['organization', 'inventory_item', 'created_at'], name='inventory_i_organiz_e34142_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['organization', 'movement_type'], name='inventory_i_organiz_1d9fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['organization', 'inventory_item', 'status'], name='inventory_s_organiz_c641da_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['organization', 'source_type', 'source_key'], name='inventory_s_organiz_dfd3cc_idx'),
        ),
    ]
