import React from "react";
import { AvatarCell } from "@foundation/ui/web/Avatar";
import { Badge } from "@foundation/ui/web/Badge";
import { Button } from "@foundation/ui/web/Button";
import { Card } from "@foundation/ui/web/Card";
import { Inline } from "@foundation/ui/web/Layout";
import { Text } from "@foundation/ui/web/Text";
import { ArrowBackIcon, ArrowForwardIcon, EditIcon } from "@foundation/ui/web/Icon/AppIcons";
import type { AdminTranslate } from "@/locales/i18n";
import type { AdminStandardColumnViewModel, AdminStandardListViewModel } from "@/view-models/standard.view-model";
import styles from "./ListPage.module.css";

interface ListPageTableProps { isLoading: boolean; onPageChange: (page: number) => void; onSelectRow?: (row: any) => void; onSort: (key: string) => void; search: string; t: AdminTranslate; viewModel: AdminStandardListViewModel; }

function formatCurrencyCents(value: unknown, currency = "BRL", locale = "pt-BR"): string { if (value === undefined || value === null || value === "") return ""; const amountCents = Number(value); return Number.isFinite(amountCents) ? new Intl.NumberFormat(locale, { currency, style: "currency" }).format(amountCents / 100) : ""; }
function resolveStatusPresentation(row: Record<string, unknown>, column: AdminStandardColumnViewModel): { statusColor?: string; tone: "danger" | "neutral" | "primary" | "success" | "warning" } { const statusColor = column.statusColorKey ? row[column.statusColorKey] : undefined; const statusTone = column.statusToneKey ? row[column.statusToneKey] : undefined; return { statusColor: typeof statusColor === "string" ? statusColor : undefined, tone: statusTone === "danger" || statusTone === "primary" || statusTone === "success" || statusTone === "warning" ? statusTone : "neutral" }; }
function isStatusColumn(column: AdminStandardColumnViewModel): boolean { return column.valueType === "status" || column.key.toLowerCase().includes("status"); }

export const ListPageTable: React.FC<ListPageTableProps> = ({ isLoading, onPageChange, onSelectRow, onSort, search, t, viewModel }) => {
  const hasActiveFilters = Boolean(search.trim()) || viewModel.activeFilterCount > 0;
  const renderCell = (row: any, column: AdminStandardColumnViewModel) => { const value = row[column.key]; const label = column.valueType === "translationKey" ? t(String(value || ""), "") : String(value ?? ""); if (column.showAvatar) return <AvatarCell image={row.image} name={String(value || row.name || row.customerName || "")} />; if (column.showMedia) return <Inline gap="sm" wrap={false}>{row.image ? <img alt={String(value || "")} className={styles.mediaThumb} src={row.image} /> : null}<Text as="span" tone="default" variant="body" weight="var(--theme--typography-bold)">{label}</Text></Inline>; if (column.render) return column.render(row); if (isStatusColumn(column)) { const presentation = resolveStatusPresentation(row, column); return <Badge appearance="soft" indicator statusColor={presentation.statusColor} tone={presentation.tone}>{label}</Badge>; } return column.valueType === "currency" ? formatCurrencyCents(value, column.currency, column.locale) : label || t("common.emptyValue"); };
  return <Card className={styles.tableCard} size="sm"><div className={styles.tableScroller}><table className={styles.table}><thead><tr>{viewModel.columns.map((column) => <th aria-sort={viewModel.sortKey === column.key ? (viewModel.sortDirection === "asc" ? "ascending" : "descending") : "none"} key={column.key} scope="col">{column.sortable ? <button className={styles.sortButton} data-sorted={viewModel.sortKey === column.key || undefined} onClick={() => onSort(column.key)} type="button"><span>{t(column.labelKey, column.key)}</span><ArrowForwardIcon aria-hidden="true" className={[styles.sortMark, viewModel.sortKey === column.key && viewModel.sortDirection === "asc" ? styles.sortAscending : viewModel.sortKey === column.key ? styles.sortDescending : ""].filter(Boolean).join(" ")} /></button> : t(column.labelKey, column.key)}</th>)}{viewModel.showActions ? <th scope="col">{t("common.actions")}</th> : null}</tr></thead><tbody>{isLoading ? <tr><td className={styles.emptyCell} colSpan={viewModel.emptyColSpan}>{t("standard.loadingRows")}</td></tr> : viewModel.rows.length === 0 ? <tr><td className={styles.emptyCell} colSpan={viewModel.emptyColSpan}>{hasActiveFilters ? t("standard.emptyFiltered") : t("common.emptyState")}</td></tr> : viewModel.rows.map((row, rowIndex) => <tr key={row.id || row.code || rowIndex} onClick={() => onSelectRow?.(row)}>{viewModel.columns.map((column) => <td key={column.key}>{renderCell(row, column)}</td>)}{viewModel.showActions ? <td className={styles.actionCell}><Button aria-label={t("common.edit")} appearance="transparent" icon={<EditIcon aria-hidden="true" />} iconPosition="only" onClick={(event) => { event.stopPropagation(); onSelectRow?.(row); }} size="xs" tone="neutral">{t("common.edit")}</Button></td> : null}</tr>)}</tbody></table></div>{!isLoading && viewModel.filteredRowsTotal > 0 ? <div className={styles.tableFooter}><Text as="p" tone="muted" variant="caption">{t("standard.showingPage", undefined, { shown: viewModel.rows.length, total: viewModel.filteredRowsTotal })}</Text>{viewModel.pageCount > 1 ? <nav aria-label={t("standard.paginationAriaLabel")} className={styles.footerPagination}><Button aria-label={t("standard.previousPage")} appearance="transparent" disabled={viewModel.page === 1} icon={<ArrowBackIcon aria-hidden="true" />} iconPosition="only" onClick={() => onPageChange(viewModel.page - 1)} size="sm" tone="neutral">{t("standard.previousPage")}</Button><Button aria-label={t("standard.nextPage")} appearance="transparent" disabled={viewModel.page === viewModel.pageCount} icon={<ArrowForwardIcon aria-hidden="true" />} iconPosition="only" onClick={() => onPageChange(viewModel.page + 1)} size="sm" tone="neutral">{t("standard.nextPage")}</Button></nav> : null}</div> : null}</Card>;
};
