# Generated by Django 5.1.4 on 2026-08-28 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('orders', '0001_initial'),
        ('organizations', '0002_rename_organizatio_slug_c3d82b_idx_organizatio_slug_048085_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='orders.order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='deliveries.delivery'),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='deliverypackage',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='deliveries.delivery'),
        ),
        migrations.AddField(
            model_name='deliverypackage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='deliverystatusdefinition',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='deliverystatushistory',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverystatushistory',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='deliveries.delivery'),
        ),
        migrations.AddField(
            model_name='deliverystatushistory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['organization', 'order'], name='deliveries__organiz_a4cbf1_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['organization', 'customer', 'status_key'], name='deliveries__organiz_0e1eff_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['organization', 'status_key'], name='deliveries__organiz_324d97_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='deliveries_delivery_unique_code'),
        ),
        migrations.AddIndex(
            model_name='deliveryconfirmation',
            index=models.Index(fields=['organization', 'confirmation_type'], name='deliveries__organiz_098223_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypackage',
            index=models.Index(fields=['organization', 'delivery'], name='deliveries__organiz_c8a656_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverystatusdefinition',
            index=models.Index(fields=['organization', 'is_initial'], name='deliveries__organiz_676c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverystatusdefinition',
            index=models.Index(fields=['organization', 'sort_order'], name='deliveries__organiz_6b24f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverystatusdefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='deliveries_status_unique_key'),
        ),
        migrations.AddIndex(
            model_name='deliverystatushistory',
            index=models.Index(fields=['organization', 'delivery', 'created_at'], name='deliveries__organiz_b6a2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverystatushistory',
            index=models.Index(fields=['organization', 'to_status_key'], name='deliveries__organiz_52ea52_idx'),
        ),
    ]
