# Generated by Django 5.1.4 on 2026-08-28 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_customers_a_organiz_49c533_idx_customers_a_organiz_2186ae_idx_and_more'),
        ('deliveries', '0003_alter_deliverystatushistory_options'),
        ('orders', '0002_alter_orderstatushistory_options'),
        ('organizations', '0002_rename_organizatio_slug_c3d82b_idx_organizatio_slug_048085_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('organization', 'order'), name='deliveries_delivery_unique_order'),
        ),
    ]
