# Generated by Django 5.1.15 on 2026-09-23 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_backfill_delivery_promise'),
        ('organizations', '0002_rename_organizatio_slug_c3d82b_idx_organizatio_slug_048085_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPromisePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('min_business_days', models.PositiveIntegerField()),
                ('max_business_days', models.PositiveIntegerField()),
                ('approaching_business_days', models.PositiveIntegerField(default=2)),
                ('order_kind_keys', models.JSONField(blank=True, default=list)),
                ('subscription_plan_keys', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['organization', 'is_active', 'sort_order'], name='deliveries__organiz_a7ecb5_idx'), models.Index(fields=['organization', 'is_default'], name='deliveries__organiz_c60067_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'key'), name='deliveries_promise_policy_unique_key'), models.CheckConstraint(condition=models.Q(('min_business_days__lte', models.F('max_business_days'))), name='deliveries_promise_policy_business_days_range'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization',), name='deliveries_promise_policy_one_default')],
            },
        ),
    ]
