# Generated by Django 5.1.4 on 2026-08-28 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_rename_organizatio_slug_c3d82b_idx_organizatio_slug_048085_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('prefix', models.CharField(blank=True, max_length=24)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('template', models.CharField(default='{prefix}-{number}', max_length=80)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['key'],
                'indexes': [models.Index(fields=['organization', 'key'], name='core_codese_organiz_1f44df_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'key'), name='core_code_sequence_unique_key')],
            },
        ),
    ]
