export const clientRoutes = {
  home: "/home",
  homeTeste1: "/home-teste-1",
  homeTeste2: "/home-teste-2",
  homeTeste3: "/home-teste-3",
  homeTeste4: "/home-teste-4",
  homeTeste5: "/home-teste-5",
  homeTeste6: "/home-teste-6",
  homeTeste7: "/home-teste-7",
  homeTeste8: "/home-teste-8",
  meusPedidosTeste1: "/meus-pedidos-teste-1",
  meusPedidosTeste2: "/meus-pedidos-teste-2",
  meusPedidosTeste3: "/meus-pedidos-teste-3",
  meusPedidosTeste4: "/meus-pedidos-teste-4",
  meusPedidosTeste5: "/meus-pedidos-teste-5",
  landingTeste1: "/landing-teste-1",
  landingTeste2: "/landing-teste-2",
  landingTeste3: "/landing-teste-3",
  landingTeste4: "/landing-teste-4",
  landingTeste5: "/landing-teste-5",
  library: "/library",
  catalogo: "/catalogo",
  catalogoTeste1: "/catalogo-teste-1",
  produtos: "/montar-box",
  meusPedidos: "/meus-pedidos",
  minhaConta: "/perfil"
};
