# Generated by Django 5.1.4 on 2026-08-28 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_remove_productprice_catalog_product_price_unique_mode_and_more'),
        ('customers', '0002_rename_customers_a_organiz_49c533_idx_customers_a_organiz_2186ae_idx_and_more'),
        ('organizations', '0002_rename_organizatio_slug_c3d82b_idx_organizatio_slug_048085_idx_and_more'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('kind_key', models.SlugField(max_length=80)),
                ('status_key', models.SlugField(max_length=80)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('subtotal_cents', models.PositiveIntegerField(default=0)),
                ('discount_cents', models.PositiveIntegerField(default=0)),
                ('freight_cents', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='subscriptions.subscription')),
                ('subscription_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='subscriptions.subscriptioncycle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_snapshot', models.CharField(max_length=220)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('total_cents', models.PositiveIntegerField()),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, max_length=80)),
                ('source_key', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('measurement_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.measurementunit')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderKindDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('code_sequence_key', models.SlugField(default='orders', max_length=80)),
                ('requires_inventory', models.BooleanField(default=True)),
                ('creates_delivery', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('commercial_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_kinds', to='catalog.commercialmode')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('allowed_next_keys', models.JSONField(blank=True, default=list)),
                ('effects', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status_key', models.SlugField(blank=True, max_length=80)),
                ('to_status_key', models.SlugField(max_length=80)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'customer', 'status_key'], name='orders_orde_organiz_3c8e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'kind_key', 'status_key'], name='orders_orde_organiz_49e0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'created_at'], name='orders_orde_organiz_fdf2fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='orders_order_unique_code'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['organization', 'order'], name='orders_orde_organiz_0cb7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['organization', 'product'], name='orders_orde_organiz_88e8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['organization', 'variant'], name='orders_orde_organiz_c418a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderkinddefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='orders_kind_unique_key'),
        ),
        migrations.AddIndex(
            model_name='orderstatusdefinition',
            index=models.Index(fields=['organization', 'is_initial'], name='orders_orde_organiz_7111e8_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatusdefinition',
            index=models.Index(fields=['organization', 'sort_order'], name='orders_orde_organiz_74e063_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderstatusdefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='orders_status_unique_key'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['organization', 'order', 'created_at'], name='orders_orde_organiz_4f18ab_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['organization', 'to_status_key'], name='orders_orde_organiz_4cfb52_idx'),
        ),
    ]
