# Generated by Django 5.1.15 on 2026-09-20 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
        ('orders', '0002_alter_orderstatushistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='box_cycle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='boxes.boxcycle'),
        ),
    ]
