# Generated by Django 5.1.15 on 2026-09-20 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_collection_image_fields'),
        ('customers', '0002_rename_customers_a_organiz_49c533_idx_customers_a_organiz_2186ae_idx_and_more'),
        ('organizations', '0002_rename_organizatio_slug_c3d82b_idx_organizatio_slug_048085_idx_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BoxSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('order_creation_policy', models.CharField(choices=[('immediate', 'Immediate'), ('payment_confirmed', 'Payment confirmed')], default='payment_confirmed', max_length=24)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_subscriptions', to='customers.customer')),
                ('default_delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_subscriptions', to='customers.address')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='box_subscription', to='scheduling.schedule')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='boxes.boxtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='BoxTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_template_items', to='catalog.product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boxes.boxtemplate')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='box_template_items', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoxCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_key', models.CharField(max_length=120)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('awaiting_payment', 'Awaiting payment'), ('order_created', 'Order created'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='prepared', max_length=24)),
                ('currency', models.CharField(max_length=3)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('items_snapshot', models.JSONField(default=list)),
                ('address_snapshot', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('schedule_occurrence', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='box_cycle', to='scheduling.scheduleoccurrence')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='boxes.boxsubscription')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status', 'scheduled_for'], name='boxes_boxcy_organiz_603a25_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'subscription', 'cycle_key'), name='boxes_cycle_unique_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='boxtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='boxes_template_unique_key'),
        ),
        migrations.AddIndex(
            model_name='boxsubscription',
            index=models.Index(fields=['organization', 'customer', 'status'], name='boxes_boxsu_organiz_d056d0_idx'),
        ),
    ]
