# Generated by Django 5.1.4 on 2026-08-28 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_productvariant_attributes_measurementunit_and_more'),
        ('customers', '0002_rename_customers_a_organiz_49c533_idx_customers_a_organiz_2186ae_idx_and_more'),
        ('organizations', '0002_rename_organizatio_slug_c3d82b_idx_organizatio_slug_048085_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('key', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20)),
                ('billing_interval', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=20)),
                ('trial_days', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120)),
                ('target_type', models.CharField(choices=[('collection', 'Collection'), ('category', 'Category'), ('product', 'Product'), ('variant', 'Variant')], max_length=24)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_entitlements', to='catalog.category')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_entitlements', to='catalog.collection')),
                ('measurement_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_entitlements', to='catalog.measurementunit')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='subscriptions.plan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_entitlements', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_entitlements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('amount_cents', models.PositiveIntegerField()),
                ('billing_interval', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=20)),
                ('billing_interval_count', models.PositiveIntegerField(default=1)),
                ('price_type', models.CharField(choices=[('recurring', 'Recurring'), ('trial', 'Trial'), ('manual', 'Manual')], default='recurring', max_length=24)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='subscriptions.plan')),
            ],
            options={
                'ordering': ['amount_cents'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('past_due', 'Past due')], default='active', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('current_cycle_starts_at', models.DateTimeField(blank=True, null=True)),
                ('current_cycle_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('fulfilled', 'Fulfilled'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-starts_at', '-cycle_number'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCycleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('reserved', 'Reserved'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.subscriptioncycle')),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_items', to='subscriptions.planentitlement')),
                ('measurement_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_cycle_items', to='catalog.measurementunit')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_cycle_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_cycle_items', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['organization', 'status'], name='subscriptio_organiz_4ad441_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['organization', 'sort_order'], name='subscriptio_organiz_cf21f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='subscriptions_plan_unique_key'),
        ),
        migrations.AddIndex(
            model_name='planentitlement',
            index=models.Index(fields=['organization', 'plan', 'target_type'], name='subscriptio_organiz_9a7471_idx'),
        ),
        migrations.AddIndex(
            model_name='planentitlement',
            index=models.Index(fields=['organization', 'target_type'], name='subscriptio_organiz_99ef64_idx'),
        ),
        migrations.AddConstraint(
            model_name='planentitlement',
            constraint=models.UniqueConstraint(fields=('organization', 'plan', 'key'), name='subscriptions_entitlement_unique_key'),
        ),
        migrations.AddConstraint(
            model_name='planentitlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('collection__isnull', False), ('product__isnull', True), ('target_type', 'collection'), ('variant__isnull', True)), models.Q(('category__isnull', False), ('collection__isnull', True), ('product__isnull', True), ('target_type', 'category'), ('variant__isnull', True)), models.Q(('category__isnull', True), ('collection__isnull', True), ('product__isnull', False), ('target_type', 'product'), ('variant__isnull', True)), models.Q(('category__isnull', True), ('collection__isnull', True), ('product__isnull', True), ('target_type', 'variant'), ('variant__isnull', False)), _connector='OR'), name='subscriptions_entitlement_target_matches_type'),
        ),
        migrations.AddIndex(
            model_name='planprice',
            index=models.Index(fields=['organization', 'plan'], name='subscriptio_organiz_e1a9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='planprice',
            index=models.Index(fields=['organization', 'currency'], name='subscriptio_organiz_953699_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'customer', 'status'], name='subscriptio_organiz_e3474c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'plan', 'status'], name='subscriptio_organiz_272506_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncycle',
            index=models.Index(fields=['organization', 'subscription', 'status'], name='subscriptio_organiz_1bf6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncycle',
            index=models.Index(fields=['organization', 'starts_at', 'ends_at'], name='subscriptio_organiz_bf7c93_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioncycle',
            constraint=models.UniqueConstraint(fields=('organization', 'subscription', 'cycle_number'), name='subscriptions_cycle_unique_number'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncycleitem',
            index=models.Index(fields=['organization', 'cycle', 'status'], name='subscriptio_organiz_02f13d_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncycleitem',
            index=models.Index(fields=['organization', 'entitlement'], name='subscriptio_organiz_350cc1_idx'),
        ),
    ]
