# Generated by Django 5.1.4 on 2026-09-09 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_customers_a_organiz_49c533_idx_customers_a_organiz_2186ae_idx_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='default_delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customers.address'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='delivery_preferences',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='delivery_window',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='subscription',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='preferred_delivery_day',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
