# Generated by Django 5.1.4 on 2026-08-27 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('organizations', '0002_rename_organizatio_slug_c3d82b_idx_organizatio_slug_048085_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='catalogavailability',
            new_name='catalog_cat_organiz_52c646_idx',
            old_name='catalog_cat_organiz_b55681_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='catalog_cat_organiz_e2d231_idx',
            old_name='catalog_cat_organiz_81c46f_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='catalog_cat_organiz_c1c133_idx',
            old_name='catalog_cat_organiz_3bcfa0_idx',
        ),
        migrations.RenameIndex(
            model_name='collection',
            new_name='catalog_col_organiz_a63f83_idx',
            old_name='catalog_col_organiz_5ff963_idx',
        ),
        migrations.RenameIndex(
            model_name='collection',
            new_name='catalog_col_organiz_1d8c77_idx',
            old_name='catalog_col_organiz_10eb6c_idx',
        ),
        migrations.RenameIndex(
            model_name='collectionproduct',
            new_name='catalog_col_organiz_31c2a4_idx',
            old_name='catalog_col_organiz_62cd1c_idx',
        ),
        migrations.RenameIndex(
            model_name='collectionproduct',
            new_name='catalog_col_organiz_0cdca4_idx',
            old_name='catalog_col_organiz_23ac93_idx',
        ),
        migrations.RenameIndex(
            model_name='commercialmode',
            new_name='catalog_com_organiz_9205b9_idx',
            old_name='catalog_com_organiz_929d31_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_organiz_101ccc_idx',
            old_name='catalog_pro_organiz_882f5d_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_organiz_3684c6_idx',
            old_name='catalog_pro_organiz_b9ecff_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_organiz_7ccbb2_idx',
            old_name='catalog_pro_organiz_4d855a_idx',
        ),
        migrations.RenameIndex(
            model_name='productmedia',
            new_name='catalog_pro_organiz_0eb6c5_idx',
            old_name='catalog_pro_organiz_77e2fe_idx',
        ),
        migrations.RenameIndex(
            model_name='productprice',
            new_name='catalog_pro_organiz_75d9df_idx',
            old_name='catalog_pro_organiz_f9f2e5_idx',
        ),
        migrations.RenameIndex(
            model_name='productprice',
            new_name='catalog_pro_organiz_3396ca_idx',
            old_name='catalog_pro_organiz_6fc6f1_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='catalog_pro_organiz_9cefd3_idx',
            old_name='catalog_pro_organiz_40a83b_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='catalog_pro_organiz_793fdf_idx',
            old_name='catalog_pro_organiz_554870_idx',
        ),
        migrations.AlterField(
            model_name='catalogavailability',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='collectionproduct',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='commercialmode',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
    ]
