# Generated by Django 5.1.4 on 2026-08-27 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_catalog_cat_organiz_b55681_idx_catalog_cat_organiz_52c646_idx_and_more'),
        ('organizations', '0002_rename_organizatio_slug_c3d82b_idx_organizatio_slug_048085_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'category__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='productprice',
            name='catalog_product_price_unique_mode',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_organiz_3684c6_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='productprice',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_prices', to='catalog.collection'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_type',
            field=models.CharField(choices=[('base', 'Base'), ('promotional', 'Promotional'), ('subscription', 'Subscription'), ('campaign', 'Campaign'), ('manual', 'Manual')], default='base', max_length=24),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['organization', 'collection', 'price_type'], name='catalog_pro_organiz_d98601_idx'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(fields=('organization', 'product', 'variant', 'commercial_mode', 'collection', 'price_type'), name='catalog_product_price_unique_mode'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_links', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['organization', 'product', 'sort_order'], name='catalog_pro_organiz_009650_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['organization', 'category'], name='catalog_pro_organiz_82fae5_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'product', 'category'), name='catalog_product_category_unique'),
        ),
    ]
