# Generated by Django 5.1.4 on 2026-08-27 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productcategory_and_more'),
        ('organizations', '0002_rename_organizatio_slug_c3d82b_idx_organizatio_slug_048085_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField()),
                ('name', models.CharField(max_length=120)),
                ('symbol', models.CharField(blank=True, max_length=24)),
                ('kind', models.CharField(choices=[('weight', 'Weight'), ('count', 'Count'), ('package', 'Package'), ('volume', 'Volume'), ('service', 'Service')], max_length=24)),
                ('decimal_places', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='measurement_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.measurementunit'),
        ),
        migrations.AddIndex(
            model_name='measurementunit',
            index=models.Index(fields=['organization', 'kind'], name='catalog_mea_organiz_c0c5d8_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementunit',
            index=models.Index(fields=['organization', 'is_active'], name='catalog_mea_organiz_15bd11_idx'),
        ),
        migrations.AddConstraint(
            model_name='measurementunit',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='catalog_measurement_unit_unique_key'),
        ),
    ]
