# Generated by Django 5.1.4 on 2026-08-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productvariant_attributes_measurementunit_and_more'),
        ('organizations', '0002_rename_organizatio_slug_c3d82b_idx_organizatio_slug_048085_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productprice',
            name='catalog_product_price_unique_mode',
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('collection__isnull', True), ('variant__isnull', True)), fields=('organization', 'product', 'commercial_mode', 'price_type'), name='catalog_price_unique_product_mode'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('collection__isnull', True), ('variant__isnull', False)), fields=('organization', 'product', 'variant', 'commercial_mode', 'price_type'), name='catalog_price_unique_variant_mode'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('collection__isnull', False), ('variant__isnull', True)), fields=('organization', 'product', 'commercial_mode', 'collection', 'price_type'), name='catalog_price_unique_collection_mode'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('collection__isnull', False), ('variant__isnull', False)), fields=('organization', 'product', 'variant', 'commercial_mode', 'collection', 'price_type'), name='catalog_price_unique_variant_collection_mode'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('organization', 'sku'), name='catalog_product_variant_unique_sku'),
        ),
    ]
