import type { SemiComposedConfig, SemiElevationLevel, SemiLevel, SurfaceAppearance, SurfaceTone } from "./contract";

const levels = ["2xs", "xs", "sm", "md", "lg", "xl", "2xl", "3xl"] as const satisfies readonly SemiLevel[];
const elevationLevels = ["none", ...levels] as const satisfies readonly SemiElevationLevel[];
const byLevel = <T>(factory: (level: SemiLevel, index: number) => T) =>
  Object.fromEntries(levels.map((level, index) => [level, factory(level, index)])) as Record<SemiLevel, T>;
const byElevation = <T>(factory: (level: SemiElevationLevel, index: number) => T) =>
  Object.fromEntries(elevationLevels.map((level, index) => [level, factory(level, index)])) as Record<SemiElevationLevel, T>;

export const DEFAULT_SEMI_COMPOSED_CONFIG: SemiComposedConfig = {
  text: byLevel((level, index) => ({
    fontToken: index >= 5 ? "headingFamily" : "bodyFamily",
    sizeToken: level,
    weightToken: index >= 5 ? "weightBold" : "weightSemibold",
    lineHeightToken: level,
    letterSpacingToken: level,
    toneToken: "text",
  })),
  icon: byLevel((level) => ({
    sizeToken: level,
    strokeToken: level,
    fillToken: "none",
    toneToken: "text",
  })),
  stroke: byElevation((level) => ({
    widthToken: level,
    styleToken: "solid",
    toneToken: "border",
    opacityToken: level === "none" ? "invisible" : "opaque",
  })),
  outerElevation: byElevation((level) => ({
    level,
    colorToken: "text",
  })),
  innerElevation: byElevation((level) => ({
    level,
    colorToken: "text",
    opacityToken: level === "none" ? "invisible" : "subtle",
  })),
  stateLayer: byLevel(() => ({
    hoverToneToken: "hover",
    hoverOpacityToken: "hover",
    pressedToneToken: "pressed",
    pressedOpacityToken: "pressed",
    selectedToneToken: "selection",
    selectedOpacityToken: "pressed",
  })),
  focusRing: byLevel((level) => ({
    widthToken: level === "2xs" || level === "xs" ? "sm" : "md",
    offsetToken: "2xs",
    radiusToken: "lg",
    toneToken: "focusRing",
  })),
  motion: byLevel((level) => ({
    durationToken: level === "2xs" || level === "xs" ? "durationFast" : "durationNormal",
    easingToken: "easingStandard",
    pressedScaleToken: level === "2xs" || level === "xs" ? "scaleDown2xs" : "scaleDownXs",
  })),
  disabled: byLevel((level) => ({
    opacityToken: "disabled",
    toneToken: "textDisabled",
    cursor: "not-allowed",
  })),
  glass: byLevel((level) => ({
    blurToken: level,
    borderOpacityToken: level,
    noiseToken: level,
    opacityToken: "glass",
    stroke: {
      widthToken: "xs",
      styleToken: "solid",
      toneToken: "glassBorder",
      opacityToken: "opaque",
    },
    tintOpacityToken: level,
  })),
  gradient: byLevel((level) => ({
    angleToken: level,
    directionToken: "diagonalForward",
    fromPositionToken: level,
    intensityToken: level,
    opacityToken: "opaque",
    stops: [
      { colorToken: "primary", position: 0 },
      { colorToken: "accent", position: 100 },
    ],
    toPositionToken: level,
  })),
  surface: byLevel((level, index) => ({
    radiusToken: index <= 1 ? "sm" : "md",
    strokeLevel: "xs",
    outerElevationLevel: index <= 1 ? "xs" : "none",
    innerElevationLevel: "none",
    glassLevel: level,
    gradientLevel: level,
  })),
  surfaceAppearance: {
    solid: {
      material: "solid",
      bgOpacityToken: "opaque",
      borderOpacityToken: "opaque",
      useToneSurface: false,
      useGradient: false,
      useGlass: false,
    },
    soft: {
      material: "soft",
      bgOpacityToken: "opaque",
      borderOpacityToken: "subtle",
      useToneSurface: true,
      useGradient: false,
      useGlass: false,
    },
    outline: {
      material: "outline",
      bgOpacityToken: "invisible",
      borderOpacityToken: "opaque",
      useToneSurface: false,
      useGradient: false,
      useGlass: false,
    },
    transparent: {
      material: "transparent",
      bgOpacityToken: "invisible",
      borderOpacityToken: "invisible",
      useToneSurface: false,
      useGradient: false,
      useGlass: false,
    },
    glass: {
      material: "glass",
      bgOpacityToken: "glass",
      borderOpacityToken: "opaque",
      useToneSurface: false,
      useGradient: false,
      useGlass: true,
    },
    gradient: {
      material: "gradient",
      bgOpacityToken: "opaque",
      borderOpacityToken: "opaque",
      useToneSurface: false,
      useGradient: true,
      useGlass: false,
    },
  } satisfies SemiComposedConfig["surfaceAppearance"] & Record<SurfaceAppearance, SemiComposedConfig["surfaceAppearance"][SurfaceAppearance]>,
  surfaceTone: {
    neutral: {
      bgToken: "surface",
      fgToken: "text",
      borderToken: "border",
      stateToneToken: "hover",
      softBgToken: "surfaceMuted",
      gradientFromToken: "surfaceElevated",
      gradientToToken: "surfaceMuted",
    },
    primary: {
      bgToken: "primary",
      fgToken: "primaryText",
      borderToken: "primary",
      stateToneToken: "hover",
      softBgToken: "primarySoft",
      gradientFromToken: "primary",
      gradientToToken: "accent",
    },
    success: {
      bgToken: "success",
      fgToken: "successText",
      borderToken: "successBorder",
      stateToneToken: "hover",
      softBgToken: "successSurface",
      gradientFromToken: "success",
      gradientToToken: "confirmation",
    },
    warning: {
      bgToken: "warning",
      fgToken: "warningText",
      borderToken: "warningBorder",
      stateToneToken: "hover",
      softBgToken: "warningSurface",
      gradientFromToken: "warning",
      gradientToToken: "required",
    },
    danger: {
      bgToken: "danger",
      fgToken: "dangerText",
      borderToken: "dangerBorder",
      stateToneToken: "hover",
      softBgToken: "dangerSurface",
      gradientFromToken: "danger",
      gradientToToken: "dangerBorder",
    },
    accent: {
      bgToken: "accent",
      fgToken: "accentText",
      borderToken: "accentBorder",
      stateToneToken: "hover",
      softBgToken: "accentSurface",
      gradientFromToken: "accent",
      gradientToToken: "primary",
    },
  } satisfies SemiComposedConfig["surfaceTone"] & Record<SurfaceTone, SemiComposedConfig["surfaceTone"][SurfaceTone]>,
};
