export const dashboardConfig = {
  screenKey: "dashboard",
  screenType: "dashboard",
  titleKey: "dashboard.title",
  subtitleKey: "dashboard.subtitle",
  headerBadge: {
    labelKey: "dashboard.headerBadge",
    tone: "primary",
  },
  dataSource: {
    fallbackOnError: false,
    key: "dashboard",
  },
  layout: {
    atmosphere: "transparent",
    attention: { columns: 3, gap: "sm" },
    kpis: { columns: 4, gap: "md" },
    panels: { columns: 3, gap: "md" },
    usefulColumns: 20,
  },
  widgets: [
    {
      iconKey: "revenue",
      key: "mrr",
      surface: { appearance: "glass", tone: "neutral" },
      titleKey: "dashboard.kpis.mrr",
    },
    {
      iconKey: "subscribers",
      key: "subscribers",
      surface: { appearance: "glass", tone: "neutral" },
      titleKey: "dashboard.kpis.activeSubscribers",
    },
    {
      iconKey: "deliveries",
      key: "deliveries",
      surface: { appearance: "glass", tone: "neutral" },
      titleKey: "dashboard.kpis.pendingDeliveries",
    },
    {
      iconKey: "retention",
      key: "retention",
      surface: { appearance: "glass", tone: "neutral" },
      titleKey: "dashboard.kpis.retentionRate",
    },
  ],
  panels: [
    {
      descriptionKey: "dashboard.panels.revenue.description",
      iconKey: "revenue",
      key: "revenue",
      metrics: [
        { key: "mrr", labelKey: "dashboard.metrics.estimatedRecurringRevenue" },
        { key: "orders", labelKey: "dashboard.metrics.ordersInPanel" },
      ],
      surface: { appearance: "solid", tone: "neutral" },
      titleKey: "dashboard.panels.revenue.title",
    },
    {
      descriptionKey: "dashboard.panels.club.description",
      iconKey: "subscribers",
      key: "club",
      metrics: [
        { key: "subscribers", labelKey: "dashboard.metrics.activeSubscribers" },
        { key: "pastDueSubscriptions", labelKey: "dashboard.metrics.pastDueSubscriptions", tone: "warning" },
        { key: "cancelledSubscriptions", labelKey: "dashboard.metrics.cancelledSubscriptions", tone: "danger" },
      ],
      surface: { appearance: "solid", tone: "neutral" },
      titleKey: "dashboard.panels.club.title",
    },
    {
      descriptionKey: "dashboard.panels.operation.description",
      iconKey: "deliveries",
      key: "operation",
      metrics: [
        { key: "deliveries", labelKey: "dashboard.metrics.deliveriesInQueue", tone: "warning" },
        { key: "readyDeliveries", labelKey: "dashboard.metrics.readyDeliveries", tone: "primary" },
        { key: "outForDelivery", labelKey: "dashboard.metrics.outForDelivery", tone: "success" },
      ],
      surface: { appearance: "solid", tone: "neutral" },
      titleKey: "dashboard.panels.operation.title",
    },
  ],
  attention: {
    descriptionKey: "dashboard.attention.description",
    items: [
      {
        action: { iconKey: "arrow", labelKey: "dashboard.attention.actions.viewSubscriptions", routeKey: "assinaturas" },
        descriptionKey: "dashboard.attention.items.pastDueSubscriptions.description",
        iconKey: "subscribers",
        key: "pastDueSubscriptions",
        titleKey: "dashboard.attention.items.pastDueSubscriptions.title",
        tone: "warning",
      },
      {
        action: { iconKey: "arrow", labelKey: "dashboard.attention.actions.viewDeliveries", routeKey: "deliveries" },
        descriptionKey: "dashboard.attention.items.deliveries.description",
        iconKey: "deliveries",
        key: "deliveries",
        titleKey: "dashboard.attention.items.deliveries.title",
        tone: "warning",
      },
      {
        action: { iconKey: "arrow", labelKey: "dashboard.attention.actions.viewOrders", routeKey: "pedidos" },
        descriptionKey: "dashboard.attention.items.orders.description",
        iconKey: "orders",
        key: "openOrders",
        titleKey: "dashboard.attention.items.orders.title",
        tone: "primary",
      },
    ],
    surface: { appearance: "glass", tone: "neutral" },
    titleKey: "dashboard.attention.title",
  },
  recentOrders: {
    action: { iconKey: "arrow", labelKey: "dashboard.viewAllBoxes", routeKey: "pedidos" },
    columns: [
      { key: "order", labelKey: "dashboard.tableHeaders.order" },
      { key: "member", labelKey: "dashboard.tableHeaders.member" },
      { key: "plan", labelKey: "dashboard.tableHeaders.plan" },
      { key: "box", labelKey: "dashboard.tableHeaders.box" },
      { key: "status", labelKey: "dashboard.tableHeaders.status" },
      { key: "date", labelKey: "dashboard.tableHeaders.date" },
    ],
    iconKey: "boxes",
    limit: 10,
    surface: { appearance: "glass", tone: "neutral" },
    titleKey: "dashboard.tableTitle",
  },
  plans: {
    columns: [
      { key: "plan", labelKey: "dashboard.planTableHeaders.plan" },
      { key: "price", labelKey: "dashboard.planTableHeaders.price" },
      { key: "recurrence", labelKey: "dashboard.planTableHeaders.recurrence" },
      { key: "items", labelKey: "dashboard.planTableHeaders.items" },
      { key: "subscribers", labelKey: "dashboard.planTableHeaders.subscribers" },
      { key: "status", labelKey: "dashboard.planTableHeaders.status" },
    ],
    surface: { appearance: "glass", tone: "neutral" },
    titleKey: "dashboard.plansTableTitle",
  },
};
