export const pedidosConfig = {
  screenKey: "pedidos",
  screenType: "standard",
  entityNameKey: "entities.order",
  dataSource: { key: "pedidos", fallbackOnError: false },
  listPage: {
    titleKey: "pedidos.title",
    subtitleKey: "pedidos.subtitle",
    actionLabelKey: "pedidos.ctaAdd",
    searchPlaceholderKey: "pedidos.searchPlaceholder",
    defaultSort: { key: "code", direction: "desc" },
    columns: [
      { key: "code", labelKey: "pedidos.tableHeaders.code" },
      { key: "customerName", labelKey: "pedidos.tableHeaders.customerName", showAvatar: true },
      { key: "kindLabel", labelKey: "pedidos.tableHeaders.kindLabel" },
      { key: "statusLabel", labelKey: "pedidos.tableHeaders.status", valueType: "status", statusColorKey: "statusColor", statusToneKey: "statusTone" },
      { key: "deliveryDeadline", labelKey: "pedidos.tableHeaders.deliveryDeadline", sortValueKey: "deliveryDeadlineSortValue" },
      { key: "deliveryPromiseStatusLabelKey", labelKey: "pedidos.tableHeaders.deliveryPromise", sortValueKey: "deliveryPromisePriority", valueType: "translationKey", statusToneKey: "deliveryPromiseStatusTone" },
      { key: "deliveryBusinessDays", labelKey: "pedidos.tableHeaders.deliveryBusinessDays" },
      { key: "totalFormatted", labelKey: "pedidos.tableHeaders.total", sortValueKey: "totalCents" },
    ],
    filters: [
      { key: "customerId", labelKey: "pedidos.fields.customer", source: "clientes" },
      { key: "kindKey", labelKey: "pedidos.fields.kind", source: "tiposPedido" },
      {
        key: "status",
        labelKey: "common.status",
        source: "orderStatuses",
      },
      {
        key: "deliveryPromiseState",
        labelKey: "pedidos.filters.deliveryPromise",
        options: [
          { value: "on_track", labelKey: "pedidos.deliveryPromise.states.on_track" },
          { value: "approaching", labelKey: "pedidos.deliveryPromise.states.approaching" },
          { value: "due_today", labelKey: "pedidos.deliveryPromise.states.due_today" },
          { value: "overdue", labelKey: "pedidos.deliveryPromise.states.overdue" }
        ]
      },
    ],
    workflow: {
      actionKey: "transition",
      card: { idKey: "id", metadataKeys: ["workflowLabel"], subtitleKey: "customerName", titleKey: "code" },
      defaultView: "table",
      emptyKey: "pedidos.workflow.empty",
      fieldKey: "statusKey",
      moveLabelKey: "pedidos.workflow.moveLabel",
      openLabelKey: "pedidos.workflow.statusLabel",
      source: "orderStatuses",
      viewLabelKey: "pedidos.workflow.viewLabel",
      viewModes: [
        { labelKey: "pedidos.workflow.views.table", value: "table" },
        { labelKey: "pedidos.workflow.views.kanban", value: "kanban" },
      ],
    },
  },
  detailPage: {
    titleKey: "pedidos.detail.title",
    displayNameKey: "code",
    header: {
      meta: [
        { key: "customerName", labelKey: "pedidos.fields.customer" },
        { key: "kindLabel", labelKey: "pedidos.fields.kind" },
      ],
    },
    tabs: [
      {
        id: "dados",
        labelKey: "pedidos.detail.tabs.data",
        emptyKey: "pedidos.detail.emptyData",
        sections: [
          {
            key: "items",
            type: "lineItems",
            titleKey: "pedidos.detail.tabs.items",
            iconIntent: "box",
            grid: { desktop: 1, tablet: 1, mobile: 1 },
            itemsKey: "items",
            labelKey: "pedidos.fields.items",
            editable: true,
            addLabelKey: "pedidos.items.add",
            columns: [
              { key: "nameSnapshot", labelKey: "pedidos.items.name", type: "text", align: "start" },
              { key: "quantityLabel", labelKey: "pedidos.items.quantity", type: "text", align: "end" },
              { key: "unitPriceFormatted", labelKey: "pedidos.items.unitPrice", type: "text", align: "end" },
              { key: "totalFormatted", labelKey: "pedidos.items.total", type: "text", align: "end" },
            ],
            edit: {
              columns: [
                { key: "productKey", labelKey: "pedidos.items.product", type: "select", source: "produtosPedido", required: true, align: "start", span: 4, presentation: "media", searchable: true, searchPlaceholderKey: "pedidos.items.searchProductPlaceholder", searchEmptyKey: "pedidos.items.emptyProductSearch", writeOptionMeta: { variantSku: "variantSku", measurementUnitKey: "measurementUnitKey", maxQuantity: "maxQuantity" } },
                { key: "quantity", labelKey: "pedidos.items.quantity", type: "number", format: "decimalBR", required: true, suffixKey: "measurementUnitKey", maxKey: "maxQuantity", align: "end", span: 2 },
              ],
            },
          },
          {
            key: "summary",
            type: "fields",
            titleKey: "pedidos.detail.tabs.data",
            iconIntent: "identity",
            grid: { desktop: 3, tablet: 2, mobile: 1 },
            fields: [
              { key: "code", labelKey: "pedidos.fields.code" },
              { key: "customerName", labelKey: "pedidos.fields.customer" },
              { key: "kindLabel", labelKey: "pedidos.fields.kind" },
              { key: "recurrenceLabel", labelKey: "pedidos.fields.recurrence" },
              { key: "subscriptionCycleWindow", labelKey: "pedidos.fields.subscriptionCycleWindow" },
              { key: "boxRecurrenceDay", labelKey: "pedidos.fields.boxRecurrenceDay" },
              { key: "addressLabel", labelKey: "pedidos.fields.address" },
              {
                key: "statusKey",
                labelKey: "pedidos.workflow.moveLabel",
                display: { key: "statusLabel", type: "text", valueType: "optionLabel" },
                statusToneKey: "statusTone",
                edit: { type: "select", source: "orderStatuses", transitionOnly: true },
              },
              { key: "deliveryDeadline", labelKey: "pedidos.tableHeaders.deliveryDeadline" },
              { key: "deliveryPromiseStatusLabelKey", labelKey: "pedidos.tableHeaders.deliveryPromise", valueType: "translationKey", statusToneKey: "deliveryPromiseStatusTone" },
              { key: "deliveryBusinessDays", labelKey: "pedidos.tableHeaders.deliveryBusinessDays" },
              { key: "totalFormatted", labelKey: "pedidos.fields.total" },
              { key: "createdAt", labelKey: "pedidos.fields.createdAt" },
              { key: "notes", labelKey: "pedidos.fields.notes", type: "textarea", layout: "full" },
            ],
          },
        ],
      },
      {
        id: "assinatura",
        hideWhenEmpty: true,
        labelKey: "pedidos.detail.tabs.subscription",
        emptyKey: "pedidos.detail.emptySubscription",
        sections: [{ key: "subscription", type: "fields", titleKey: "pedidos.detail.tabs.subscription", iconIntent: "commerce", grid: { desktop: 3, tablet: 2, mobile: 1 }, fields: [
          { key: "recurrenceLabel", labelKey: "pedidos.fields.recurrence" },
          { key: "subscriptionCycleLabel", labelKey: "pedidos.fields.subscriptionCycle" },
          { key: "subscriptionCycleStatus", labelKey: "pedidos.fields.subscriptionCycleStatus", display: { key: "subscriptionCycleStatusLabelKey", valueType: "translationKey" } },
        ] }],
      },
      {
        id: "royalBox",
        hideWhenEmpty: true,
        labelKey: "pedidos.detail.tabs.royalBox",
        emptyKey: "pedidos.detail.emptyRoyalBox",
        sections: [{ key: "royalBox", type: "fields", titleKey: "pedidos.fields.recurrence", iconIntent: "box", grid: { desktop: 3, tablet: 2, mobile: 1 }, fields: [
          { key: "boxRecurrenceDay", labelKey: "pedidos.fields.boxRecurrenceDay" },
          { key: "boxTemplateName", labelKey: "pedidos.fields.boxTemplate" },
          { key: "boxCycleLabel", labelKey: "pedidos.fields.boxCycle" },
          { key: "boxCycleScheduledFor", labelKey: "pedidos.fields.boxScheduledFor" },
          { key: "boxCycleStatus", labelKey: "pedidos.fields.boxCycleStatus", display: { key: "boxCycleStatusLabelKey", valueType: "translationKey" } },
          { key: "boxOrderCreationPolicy", labelKey: "pedidos.fields.boxOrderCreationPolicy", display: { key: "boxOrderCreationPolicyLabelKey", valueType: "translationKey" } },
        ] }],
      },
      {
        id: "entrega",
        hideWhenEmpty: true,
        labelKey: "pedidos.detail.tabs.delivery",
        emptyKey: "pedidos.detail.emptyDelivery",
        sections: [{
          key: "promise",
          type: "fields",
          titleKey: "pedidos.tableHeaders.deliveryPromise",
          iconIntent: "delivery",
          grid: { desktop: 3, tablet: 2, mobile: 1 },
          fields: [
            { key: "deliveryDeadline", labelKey: "pedidos.tableHeaders.deliveryDeadline" },
            { key: "deliveryPromiseStatusLabelKey", labelKey: "pedidos.tableHeaders.deliveryPromise", valueType: "translationKey", statusToneKey: "deliveryPromiseStatusTone" },
            { key: "deliveryBusinessDays", labelKey: "pedidos.tableHeaders.deliveryBusinessDays" },
          ],
        }, {
          key: "deliveries",
          type: "lineItems",
          titleKey: "pedidos.detail.tabs.delivery",
          iconIntent: "delivery",
          grid: { desktop: 1, tablet: 1, mobile: 1 },
          itemsKey: "deliveries",
          labelKey: "pedidos.fields.deliveries",
          columns: [
            { key: "code", labelKey: "pedidos.deliveries.code", type: "text", detailScreenKey: "deliveries" },
            { key: "statusLabel", labelKey: "pedidos.deliveries.status", type: "text" },
            { key: "address", labelKey: "pedidos.deliveries.address", type: "text" },
            { key: "confirmationCode", labelKey: "pedidos.deliveries.confirmationCode", type: "text" },
            { key: "promisedDeliveryStartsOn", labelKey: "pedidos.deliveries.promisedDeliveryStartsOn", type: "text" },
            { key: "promisedDeliveryByOn", labelKey: "pedidos.deliveries.promisedDeliveryByOn", type: "text" },
            { key: "deliveryPromiseStatusLabelKey", labelKey: "pedidos.tableHeaders.deliveryPromise", type: "text", valueType: "translationKey" },
            { key: "deliveryBusinessDays", labelKey: "pedidos.tableHeaders.deliveryBusinessDays", type: "text" },
            { key: "notes", labelKey: "pedidos.deliveries.notes", type: "text" },
          ],
        }],
      },
    ],
  },
  addPage: {
    titleKey: "pedidos.add.title",
    submitLabelKey: "pedidos.add.submit",
    sections: [
      {
        key: "data",
        titleKey: "pedidos.add.sections.data",
        fields: [
          { key: "customerId", labelKey: "pedidos.fields.customer", type: "select", source: "clientes", required: true },
          { key: "kindKey", labelKey: "pedidos.fields.kind", type: "select", source: "tiposPedidoCriacaoManual", required: true },
          { key: "subscriptionId", labelKey: "pedidos.fields.subscription", type: "select", source: "assinaturas" },
          { key: "subscriptionCycleId", labelKey: "pedidos.fields.subscriptionCycle", type: "select", source: "ciclosAssinatura" },
          { key: "addressId", labelKey: "pedidos.fields.address", type: "select", source: "enderecos" },
          { key: "notes", labelKey: "pedidos.fields.notes", type: "textarea" },
        ],
      },
      {
        key: "items",
        titleKey: "pedidos.add.sections.items",
        fields: [
          {
            key: "items",
            labelKey: "pedidos.fields.items",
            type: "lineItems",
            required: true,
            addLabelKey: "pedidos.items.add",
            columns: [
              { key: "productKey", labelKey: "pedidos.items.product", type: "select", source: "produtosPedido", required: true, span: 4, presentation: "media", searchable: true, searchPlaceholderKey: "pedidos.items.searchProductPlaceholder", searchEmptyKey: "pedidos.items.emptyProductSearch", writeOptionMeta: { variantSku: "variantSku", measurementUnitKey: "measurementUnitKey", maxQuantity: "maxQuantity" } },
              { key: "quantity", labelKey: "pedidos.items.quantity", type: "number", format: "decimalBR", required: true, suffixKey: "measurementUnitKey", maxKey: "maxQuantity", span: 2 },
            ],
          },
        ],
      },
    ],
  },
};
