# Generated by Django 5.1.4 on 2026-08-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationmember',
            new_name='accounts_or_organiz_793589_idx',
            old_name='accounts_or_organiz_c4cd31_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmember',
            new_name='accounts_or_user_id_25b404_idx',
            old_name='accounts_or_user_id_526cfa_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_token_h_2771ed_idx',
            old_name='accounts_pa_token_h_60d6e6_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_expires_01b447_idx',
            old_name='accounts_pa_expires_95be43_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_email_74c8d6_idx',
            old_name='accounts_us_email_811095_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_is_acti_a5841d_idx',
            old_name='accounts_us_is_acti_f16f7a_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
