# Generated by Django 5.1.4 on 2026-08-27 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0002_rename_organizatio_slug_c3d82b_idx_organizatio_slug_048085_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='address',
            new_name='customers_a_organiz_2186ae_idx',
            old_name='customers_a_organiz_49c533_idx',
        ),
        migrations.RenameIndex(
            model_name='address',
            new_name='customers_a_organiz_ed38fa_idx',
            old_name='customers_a_organiz_94f767_idx',
        ),
        migrations.RenameIndex(
            model_name='address',
            new_name='customers_a_custome_d08d94_idx',
            old_name='customers_a_custome_21542d_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_organiz_628fa0_idx',
            old_name='customers_c_organiz_d6cb52_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_organiz_d03b43_idx',
            old_name='customers_c_organiz_20db34_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_organiz_d39d52_idx',
            old_name='customers_c_organiz_62e208_idx',
        ),
        migrations.RenameIndex(
            model_name='customernote',
            new_name='customers_c_organiz_5d28b4_idx',
            old_name='customers_c_organiz_e1aa66_idx',
        ),
        migrations.RenameIndex(
            model_name='customernote',
            new_name='customers_c_author__67863b_idx',
            old_name='customers_c_author__ad6642_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmethodref',
            new_name='customers_p_organiz_334cf9_idx',
            old_name='customers_p_organiz_fd158c_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmethodref',
            new_name='customers_p_custome_9f8f02_idx',
            old_name='customers_p_custome_8598df_idx',
        ),
        migrations.AlterField(
            model_name='address',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentmethodref',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
    ]
