# Generated by Django 5.1.15 on 2026-09-20 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_rename_organizatio_slug_c3d82b_idx_organizatio_slug_048085_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('recurrence_rule', models.JSONField(default=dict)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('cutoff_minutes', models.PositiveIntegerField(default=0)),
                ('effect_key', models.SlugField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurrence_key', models.CharField(max_length=120)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='scheduling.schedule')),
            ],
            options={
                'ordering': ['scheduled_for', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['organization', 'status'], name='scheduling__organiz_c06c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['organization', 'effect_key', 'status'], name='scheduling__organiz_27d35f_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='scheduling_schedule_unique_key'),
        ),
        migrations.AddIndex(
            model_name='scheduleoccurrence',
            index=models.Index(fields=['organization', 'schedule', 'scheduled_for'], name='scheduling__organiz_83543b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleoccurrence',
            index=models.Index(fields=['organization', 'status', 'scheduled_for'], name='scheduling__organiz_16e525_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduleoccurrence',
            constraint=models.UniqueConstraint(fields=('organization', 'schedule', 'occurrence_key'), name='scheduling_occurrence_unique_key'),
        ),
    ]
