import type { UiAmbientEffectRecipeTokens } from "../themeBindings";

export const DEFAULT_AMBIENT_RECIPES = {
  glassCursor: {
    "2xs": { glassLevel: "2xs", intensityToken: "2xs", layer: "background", motion: "none", overlay: "none", sizeToken: "2xs" }, xs: { glassLevel: "xs", intensityToken: "xs", layer: "background", motion: "none", overlay: "none", sizeToken: "xs" }, sm: { glassLevel: "sm", intensityToken: "sm", layer: "background", motion: "2xs", overlay: "2xs", sizeToken: "sm" }, md: { glassLevel: "md", intensityToken: "md", layer: "background", motion: "xs", overlay: "xs", sizeToken: "md" }, lg: { glassLevel: "lg", intensityToken: "lg", layer: "background", motion: "sm", overlay: "sm", sizeToken: "lg" }, xl: { glassLevel: "xl", intensityToken: "xl", layer: "background", motion: "md", overlay: "md", sizeToken: "xl" }, "2xl": { glassLevel: "2xl", intensityToken: "2xl", layer: "background", motion: "lg", overlay: "lg", sizeToken: "2xl" }, "3xl": { glassLevel: "3xl", intensityToken: "3xl", layer: "background", motion: "xl", overlay: "xl", sizeToken: "3xl" },
  },
  auroraBlur: {
    "2xs": { bloomToken: "2xs", chromaToken: "2xs", fadeToken: "xs", flowDirection: "diagonalUp", flowToken: "2xs", intensityToken: "2xs", layer: "background", motion: "none", noiseToken: "lg", overlay: "none", palette: "brandAurora", sizeToken: "xs" }, xs: { bloomToken: "xs", chromaToken: "xs", fadeToken: "sm", flowDirection: "diagonalUp", flowToken: "xs", intensityToken: "xs", layer: "background", motion: "none", noiseToken: "lg", overlay: "none", palette: "brandAurora", sizeToken: "sm" }, sm: { bloomToken: "sm", chromaToken: "sm", fadeToken: "sm", flowDirection: "diagonalUp", flowToken: "sm", intensityToken: "sm", layer: "background", motion: "2xs", noiseToken: "md", overlay: "2xs", palette: "brandAurora", sizeToken: "md" }, md: { bloomToken: "md", chromaToken: "md", fadeToken: "md", flowDirection: "diagonalUp", flowToken: "md", intensityToken: "md", layer: "background", motion: "xs", noiseToken: "md", overlay: "xs", palette: "brandAurora", sizeToken: "lg" }, lg: { bloomToken: "lg", chromaToken: "lg", fadeToken: "lg", flowDirection: "diagonalUp", flowToken: "lg", intensityToken: "lg", layer: "background", motion: "sm", noiseToken: "sm", overlay: "sm", palette: "brandAurora", sizeToken: "xl" }, xl: { bloomToken: "xl", chromaToken: "xl", fadeToken: "xl", flowDirection: "diagonalDown", flowToken: "xl", intensityToken: "xl", layer: "background", motion: "md", noiseToken: "sm", overlay: "md", palette: "coolAurora", sizeToken: "2xl" }, "2xl": { bloomToken: "2xl", chromaToken: "2xl", fadeToken: "2xl", flowDirection: "diagonalDown", flowToken: "2xl", intensityToken: "2xl", layer: "background", motion: "lg", noiseToken: "xs", overlay: "lg", palette: "coolAurora", sizeToken: "3xl" }, "3xl": { bloomToken: "3xl", chromaToken: "3xl", fadeToken: "3xl", flowDirection: "orbital", flowToken: "3xl", intensityToken: "3xl", layer: "background", motion: "xl", noiseToken: "xs", overlay: "xl", palette: "coolAurora", sizeToken: "3xl" },
  },
} satisfies UiAmbientEffectRecipeTokens;

export const DEFAULT_AMBIENT_RECIPE = DEFAULT_AMBIENT_RECIPES.auroraBlur.md;
