# Generated by Django 5.1.4 on 2026-08-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_slug_048085_idx',
            old_name='organizatio_slug_c3d82b_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_status_295901_idx',
            old_name='organizatio_status_7b766f_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationdomain',
            new_name='organizatio_domain_bb7939_idx',
            old_name='organizatio_domain_d9d8a5_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationdomain',
            new_name='organizatio_organiz_bdbaf9_idx',
            old_name='organizatio_organiz_19b624_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationfeatureflag',
            new_name='organizatio_organiz_9cf8c4_idx',
            old_name='organizatio_organiz_a8c778_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationsettings',
            new_name='organizatio_organiz_bb6ec0_idx',
            old_name='organizatio_organiz_d35f6c_idx',
        ),
    ]
